---
  - hosts: localhost
    gather_facts: True         
    tasks: 
    - include: tasks/role_home_dir.yml  # sets {{ role_home_dir.stdout }}
    - include: tasks/shibboleth.yml app=nuxeo
    - include: tasks/monit.yml app=nuxeo
