---
  - hosts: localhost
    gather_facts: True         
    vars:
        ingest_front_tunnel: 52.11.19440:6379 
    tasks: 
    - include: tasks/setvars.yml  # sets {{ role_home_dir.stdout }} and hostname.stdout
    - include: tasks/shibboleth.yml app=registry  
    - include: tasks/monit.yml app=registry
    - name: put stunnel.conf in place
      template: 
        src: stunnel.conf.j2
        dest: /etc/stunnel/stunnel.conf
    - name: put init.d script in place
      copy:
        src: stunnel.init.d
        dest: /etc/init.d/stunnel
        mode: 0744
    - name: chkconfig stunnel to run at boot
      command: chkconfig --add stunnel
    - name: start stunnel in daemon mode
      command: /etc/init.d/stunnel start
    - name: check out documentation
      git: repo=https://github.com/ucldc/ucldc-docs.git version=mirror dest=~/webroot/ucldc-docs
    - name: mirror the documentation from github (cheap trick)
      command: ./mirror_docs.py chdir=~/webroot/ucldc-docs creates=~/webroot/ucldc-docs/ucldc.github.io
    - name: copy fonts for documentation
      copy: src=~/webroot/ucldc-docs/fonts dest=~/webroot/ucldc-docs/ucldc.github.io/ucldc-docs/vendor/bootstrap-partial
    - name: get the bruin icon
      get_url: url=http://ucldc.github.io/ucldc-docs/images/bruin.png  dest=~/webroot/ucldc-docs/ucldc.github.io/ucldc-docs/images/bruin.png
    - name: clone registry source code
      git: repo=https://github.com/ucldc/avram dest=~/code/avram
    - name: install registry requirements
      pip: requirements=~/code/avram/requirements.txt
   #- name: build avram environment
   #  command: ~/code/avram/init.sh creates=~/code/avram/bin/activate
    - name: setup db dump cron
      cron: name="dump django db" hour="1" minute="7" job="~/code/avram/dbdump.sh" backup=True
