---
  - hosts: localhost
    gather_facts: True         
    tasks: 
    - include: tasks/role_home_dir.yml  # sets {{ role_home_dir.stdout }}
    - include: tasks/shibboleth.yml app=registry  
    - include: tasks/monit.yml app=registry
    - name: clone registry source code
      git: repo=https://github.com/ucldc/avram dest=~/code/avram
