---
# ^^^ YAML documents must begin with the document separator "---"
# ansible playbook for initial configuration
# Notice the minus on the line below -- this starts the playbook's record
# in the YAML document. Only one playbook is allowed per YAML file.
  - hosts: localhost
#    "ansible_facts": {
#        "ansible_default_ipv4": {
#            "address": "192.35.209.164",
#        },
#        "ansible_fqdn": "nuxeo-dev.cdlib.org",
#        "ansible_hostname": "nuxeo-dev",
#        "ansible_user_id": "nuxeo",
    gather_facts: True         
    tasks: 
    - name: figure out the home directory
      shell: "getent passwd registry | cut -d: -f6"
      register: role_home_dir
    - name: create http "run" directory
      file: path=~/servers/httpd/run state=directory
    - name: make sure there is an httpd logs directory
      file: path=~/servers/httpd/logs state=directory
    - name: tedious.. make _bin_ dir
      file: path=~/servers/httpd/bin state=directory
    - name: and the _conf_ dir
      file: path=~/servers/httpd/conf state=directory
    - name: make sure DocumentRoot exists or apache will cry
      file: path=~/webroot/https-registry state=directory
    - name: generate apachectl
      template: src=templates/shib-http/apachectl.j2 dest=~/servers/httpd/bin/apachectl
    - name: make apachectl a+x
      shell: chmod a+x ~/servers/httpd/bin/apachectl
    - name: generate httpd conf
      template: src=templates/shib-http/registry-httpd.conf.j2 dest=~/servers/httpd/conf/httpd.conf
    - name: httpd conf magic its the magic number
      copy: src=~/pkg/etc/httpd/magic dest=~/servers/httpd/conf/magic
    - name: httpd config mime.types who does not like MIME?
      copy: src=~/pkg/etc/httpd/mime.types dest=~/servers/httpd/conf/mime.types
    - name: var/run for wsgi sockets
      file path=~/pkg/var/run state=directory
    - name: generate shibboleth2.xml
      template: src=templates/shibboleth/shibboleth2.xml.j2  dest=~/servers/shibboleth/etc/shibboleth/shibboleth2.xml
    - name: get incommons public key
      command: curl https://wayf.incommonfederation.org/bridge/certs/incommon.pem > ~/servers/shibboleth/etc/shibboleth/incommon.pem creates=~/servers/shibboleth/etc/shibboleth/incommon.pem
    - name: generate .monitrc
      template: src=templates/shib-http/monitrc.j2  dest=~/.monitrc mode=700
    - name: yo, monit needs a log file
      file: path=~/appstrap/monit/log state=directory
    - name: clone registry source code
      git: repo=https://github.com/ucldc/avram dest=~/code/avram
    - name: clone embedded discovery service
      git: repo=https://github.com/ucldc/js-embedded-discovery.git dest=~/code/js-embedded-discovery
    - name: bulid shibboleth EDS
      command: ./build.sh creates=~/code/js-embedded-discovery/target chdir=~/code/js-embedded-discovery/build 
