---
-   hosts: localhost
    connection: local
    gather_facts: True         
    tasks:
    - name: check_appstrap
      shell: . $HOME/appstrap/setenv.sh
    - name: figure out the home directory
      shell: "getent passwd solr | cut -d: -f6"
      register: role_home_dir
    - name: create servers tomcat bin directory
      action: file path=~/servers/tomcat/bin state=directory
    - name: create servers tomcat conf directory
      action: file path=~/servers/tomcat/conf state=directory
    - name: create servers tomcat logs directory
      action: file path=~/servers/tomcat/logs state=directory
    - name: create servers tomcat webapps directory
      action: file path=~/servers/tomcat/webapps state=directory
    - name: create servers tomcat work directory
      action: file path=~/servers/tomcat/work state=directory
    - name: create servers tomcat temp directory
      action: file path=~/servers/tomcat/temp state=directory
    - name: copy tomcat CATALINA_BASE directories and files
      action: command cp -rp ~/java/tomcat/ ~/servers/tomcat
    - name: create servers solr directory
      action: file path=~/servers/solr state=directory
    - name: copy solr config tree
      action: command cp -rp ~/appstrap/ansible/templates/solr/solr/ ~/servers/solr
    - name: install solr to tomcat
      action: copy src=~/java/solr/dist/solr-4.3.1.jar dest=~/servers/tomcat/webapps/ #restart tomcat now, to unpack solr. then change WEB-INF/web.xml
# to add  
##    <env-entry>
##       <env-entry-name>solr/home</env-entry-name>
##       <env-entry-value>/home/ec2-user/servers/solr</env-entry-value>
##       <env-entry-type>java.lang.String</env-entry-type>
##    </env-entry>
