---
-   hosts: localhost
    connection: local
    gather_facts: True         
    tasks:
    - name: check_appstrap
      shell: . $HOME/appstrap/setenv.sh
    - name: figure out the home directory
      shell: "getent passwd solr | cut -d: -f6"
      register: role_home_dir
    - name: put tomcat envvars in place
      action: copy src=./templates/solr/tomcat-setenv.bash dest=~/.tomcat-setenv.bash
    - name: put bashrc in place
      copy: src=./templates/solr/bashrc dest=~/.bashrc
    - name: put gitconfig in place
      copy: src=./templates/solr/gitconfig dest=~/.gitconfig
    - name: create servers tomcat directory
      action: file path=~/servers/tomcat state=directory
    - name: copy tomcat CATALINA_BASE directories and files
      action: shell cp -rp ~/java/tomcat/* ~/servers/tomcat
    - name: create servers solr directory
      action: file path=~/servers/solr state=directory
    - name: install .monitrc
      action: template src=./templates/solr/monitrc.j2 dest=~/.monitrc mode=0700
    - name: create servers/monit directory
      action: file path=~/servers/monit state=directory
    - name: create servers/monit/log directory
      action: file path=~/servers/monit/log state=directory
    - name: create servers/monit/bin directory
      action: file path=~/servers/monit/bin state=directory
    - name: copy monit-wrapper
      action: copy src=./templates/solr/monit-wrapper.bash dest=~/servers/monit/bin/monit-wrapper.bash mode=0755
    - name: create dc-collection solr core directory
      action: file path=~/servers/solr/dc-collection state=directory
    - name: copy solr.xml
      action: copy src=./templates/solr/solr/solr.xml dest=~/servers/solr
    - name: copy zoo.cfg
      action: copy src=./templates/solr/solr/zoo.cfg dest=~/servers/solr
    - name: copy example collection files to dc-collection
      action: shell cp -rp ~/java/solr/example/solr/collection1/* ~/servers/solr/dc-collection
    - name: copy dc-collection schema.xml into webapp
      action: copy src=./templates/solr/solr/dc-collection/conf/schema.xml dest=~/servers/solr/dc-collection/conf/
    - name: copy solr to tomcat
      action: copy src=~/java/solr/dist/solr-4.3.1.war dest=~/servers/tomcat/webapps/solr.war #restart tomcat now, to unpack solr. then change WEB-INF/web.xml
#TODO: set CATALINA_BASE AND CATALINA_HOME
    - name: copy solr logging jars to tomcat
      action: shell cp -rp ~/java/solr/dist/solrj-lib/*.jar ~/servers/tomcat/lib
    - name: start tomcat to install solr war
      action: shell ~/java/tomcat/bin/startup.sh
    - name: wait for tomcat
      action: command /bin/sleep 120
    - name: stop tomcat
      action: shell ~/java/tomcat/bin/shutdown.sh
    - name: wait for tomcat
      action: command /bin/sleep 20
    - name: replace web.xml for solr webapp
      action: copy src=./templates/solr/solr/web.xml dest=~/servers/tomcat/webapps/solr/WEB-INF/
    - name: start tomcat
      action: shell ~/java/tomcat/bin/startup.sh
