---
-   hosts: localhost
    connection: local
    gather_facts: True         
    vars:
      solr_version: 4.4.0 #TODO: get from ls?
    tasks:
    - name: check_appstrap
      shell: . $HOME/appstrap/setenv.sh
    - include: tasks/role_home_dir.yml  # sets {{ role_home_dir.stdout }}
    - name: put tomcat envvars in place
      copy: src=./templates/solr/tomcat-setenv.bash dest=~/.tomcat-setenv.bash
    - name: put bashrc in place
      copy: src=./templates/solr/bashrc dest=~/.bashrc
    - name: put gitconfig in place
      copy: src=./templates/solr/gitconfig dest=~/.gitconfig
    - include: tasks/solr/tomcat_dir_setup.yml #create dirs and copy static files
    - include: tasks/solr/monit_setup.yml
    - include: tasks/solr/config_solr_server.yml
    - name: start tomcat to install solr war
      shell: monit start tomcat
    - name: wait for tomcat
      command: /bin/sleep 30 #actually want to wait for dir webapps/solr
    - name: stop tomcat
      shell: monit stop tomcat
    - name: wait for tomcat
      command: /bin/sleep 30
    - name: replace web.xml for solr webapp
      copy: src={{ role_home_dir.stdout}}/src/ucldc_solr/web.xml dest=~/servers/tomcat/webapps/solr/WEB-INF/
    - name: start tomcat
      shell: monit validate
    - name: create init.d-monit
      template: src=./templates/solr/init.d-monit.j2 dest=~/init.d-monit
